version: '3.7'

services:
  jenkins:
    image: smartsoft001/jenkins:latest
    ports:
      - '8080:8080'
    deploy:
      replicas: 1
    volumes:
      - data1:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  data1:
